### PR TITLE
Add instructions for Talkshop Name Server

### PR DESCRIPTION
**Pull request by onggunhao**
Not sure if you guys want it to be part of the tutorial, but these additional pointers were useful for me setting up Talkshop name server. Can do the CN translation later on if it helps.

### CODE REVIEW

**Comment by jackzampolin** [comment]
I don't know if we want to commit to keeping that server up. Best not to mention it IMO. Thoughts @okwme ?

**Comment by onggunhao** [comment]
For what it's worth, it was pretty cool to connect to the Talkshop name server rather than just my local testnet. Hope you'll keep it around (at least for the early days of developer adoption!)

**Comment by okwme** [comment]
I'd hate to have to start monitoring it for inappropriate content if it got too much broad attention but agree the web server is a really fun finale to the tutorial. Maybe for now it's better to introduce the server only to in-person workshop participants and try to find a long term solution that doesn't need monitoring?

I'd also like to write a front-end tutorial for building something like the talkshop.name web app. Maybe allowing a user to spin up the front-end themselves is an eventual solution?

**Comment by onggunhao** [comment]
@okwme A frontend tutorial would be really interesting, hope you work on it

**Comment by marbar3778** [comment]
will add the current FE as a docker container in the sdk-tutorial, so people can run the tutorial with the forntend. Will close this PR in favor of that.

**Pull request closed without merging**
