### PR TITLE
update to 0.37

### PR DESCRIPTION
**Pull request by marbar3778**
- [x] make changes to code
- [x] update docs
- [x] change file structure in tutorial readme

### CODE REVIEW

**Comment by marbar3778** [comment]
I do agree with you @hschoenburg, but I was following https://github.com/cosmos/cosmos-sdk/blob/master/docs/modules/SPEC.md. If this isnt something we want to enforce or only enforce in some places then i can change it back to similar as before

**Comment by hschoenburg** [comment]
> I do agree with you @hschoenburg, but I was following https://github.com/cosmos/cosmos-sdk/blob/master/docs/modules/SPEC.md. If this isnt something we want to enforce or only enforce in some places then i can change it back to similar as before

Ah ok I didnt see that in the spec. It probably does help.

**Comment by hschoenburg** [comment]
oops didnt mean to close it just there. Approving now.

**Comment by marbar3778** [comment]
thank you, @hschoenburg

**Pull request merged**
