### PR TITLE
Add circleci

### PR DESCRIPTION
**Pull request by marbar3778**

### CODE REVIEW

**Comment by jackzampolin** [comment]
I think we might need @mircea-c 's help on this one.

**Comment by mircea-c** [comment]
Before I can add anything more here, the Vuepress site needs to be built. I don't see any of that in this repo, so I guess we have to wait for it.

**Comment by marbar3778** [comment]
can we add ci for just tests, and then we can add the docs build later?

**Comment by marbar3778** [comment]
@mircea-c is this what you mean? https://github.com/cosmos/sdk-application-tutorial/pull/144

**Comment by mircea-c** [comment]
@marbar3778 CI tests are already added to the circle file. I'm not sure why you're waiting on me. you can just go ahead and merge this right now :smile:

**Pull request merged**
