### PR TITLE
Update tutorial to use go.mod instead of dep #51

### PR DESCRIPTION
**Pull request by yangyanqing**
close: #51

### CODE REVIEW

**Comment by alexanderbez** [comment]
This should not be committing to master. Are these docs still invalid/outdated on `develop`? If not, they'll be updated once v0.34.0 is released.

**Comment by yangyanqing** [comment]
> This should not be committing to master

Branch `develop` did not exist in tutorial repository.

> Are these docs still invalid/outdated on develop? 

Which doc did you mean ?

**Comment by alexanderbez** [comment]
All your changes in this PR should be targeted against `develop`. Only `develop` merges into master.

**Comment by alexanderbez** [comment]
Ahhh ignore my comments @yangyanqing 👍

**Comment by jackzampolin** [comment]
Thank you @yangyanqing! I think there are some more updates here, but I need to do a full sweep of this tuto and will take care of it then.

**Pull request merged**
