### PR TITLE
Add Version control

### LINKED ISSUE #56: add version control

### PR DESCRIPTION
**Pull request by marbar3778**
- add version to cli

meant to replace #56 
closes #56 

Signed-off-by: Marko Baricevic <marbar3778@yahoo.com>

### CODE REVIEW

**Comment by marbar3778** [comment]
to make this work i will need to release a version of the tutorial

**Comment by hschoenburg** [comment]
Im getting an error on `Make install`

```
dolokhov ~/go-work/src/github.com/cosmos/sdk-application-tutorial versioncontorl$
dolokhov ~/go-work/src/github.com/cosmos/sdk-application-tutorial versioncontorl$ make install
go install -mod=readonly -tags "" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=NameService -X github.com/cosmos/cosmos-sdk/version.ServerName=nsd -X github.com/cosmos/cosmos-sdk/version.ClientName=nscli -X github.com/cosmos/cosmos-sdk/version.Version=0.37.0-2-g1e02aa2 -X github.com/cosmos/cosmos-sdk/version.Commit=1e02aa2a06de98c04b61c88eb19a84bf08b0840b -X "github.com/cosmos/cosmos-sdk/version.BuildTags="' ./cmd/nsd
go: updates to go.mod needed, disabled by -mod=readonly
make: *** [install] Error 1
dolokhov ~/go-work/src/github.com/cosmos/sdk-application-tutorial versioncontorl$

```

**Comment by okwme** [comment]
@hschoenburg that's weird is the error "updates to go.mod needed" or is that just the log before the error? Wanna try pulling and running again with linting and version changes?

**Comment by hschoenburg** [comment]
ah latest version works great

**Pull request merged**
